% Builds L-UQ.mltbx, the installable MATLAB toolbox package.
% Run from the repository root:  matlab -batch package_toolbox
root = fileparts(mfilename('fullpath'));
files = [string(fullfile(root, {'lmom.m','LegendreShiftPoly.m', ...
    'Identify_dist.m','Parameter_estimation.m','parameter_identify.m', ...
    'fit_best.m','PDF_l.m','CDF_l.m','Random_l.m','KLDiv.m','JSDiv.m', ...
    'demo_example.m','README.md','LICENSE','CHANGELOG.md','CITATION.cff'})), ...
    string(fullfile(root,'tests','test_uq_matlab.m')), ...
    string(fullfile(root,'tests','octave_verify.m'))];
files = files(arrayfun(@isfile, files));
opts = matlab.addons.toolbox.ToolboxOptions(root, ...
    'a3d8f2c1-7b4e-4d9a-b1c6-2e5f8a0d3c7b');
opts.ToolboxName = 'L-UQ';
opts.ToolboxVersion = '1.0.0';
opts.Summary = ['L-moments based uncertainty quantification from ', ...
    'scarce samples including extremes'];
opts.Description = ['Identify a distribution family from the L-moment ', ...
    'ratio diagram, estimate parameters in closed form with domain ', ...
    'guards and ranked fallback (fit_best), evaluate PDF/CDF/random ', ...
    'sampling, and compare fit quality via KL/JS divergence. ', ...
    'Companion Python package: lmoments-uq (PyPI).'];
opts.AuthorName = 'Deepan Jayaraman';
opts.AuthorEmail = 'deepanjayram@gmail.com';
opts.AuthorCompany = 'Indian Institute of Technology Madras';
opts.ToolboxFiles = files;
opts.ToolboxMatlabPath = root;
opts.MinimumMatlabRelease = 'R2018b';
opts.OutputFile = fullfile(root, 'L-UQ.mltbx');
matlab.addons.toolbox.packageToolbox(opts);
fprintf('packaged: %s\n', opts.OutputFile);
