% Random number generation

% Reference
% 1. J.R.M. Hosking, L-moments: analysis and estimation of distributions using linear combinations of order statistics
% 2. J.R.M. Hosking , J.R. Wallis,Regional Frequency Analysis: An approach based on L-moments.

% Name - Distribution name
% Parameter - Distribution parameter
% (m,n) - Size

% Variates are generated by inverse transform sampling: uniform draws
% from rand() pushed through the family's closed-form inverse CDF in
% luq_dist. Earlier releases called MATLAB's name-dispatching random(),
% which requires the Statistics and Machine Learning Toolbox and has no
% portable equivalent in GNU Octave.
%
% Note that the exact stream of variates therefore differs from the
% earlier random()-based implementation even for an identical rand seed;
% the distribution sampled is the same. Random streams are not
% reproducible across MATLAB and Octave in any case, so replication
% material should compare distributions, not individual draws.

% Copy right
% ADOPT Lab, IIT Madras, India

function X = Random_l(Name,Parameter,m,n)

if nargin < 4
    n = 1;
end

X = luq_dist('inv', Name, Parameter, rand(m, n));
